global:
    checkNewVersion: true
    sendAnonymousUsage: false

log:
    level: DEBUG

metrics:
    prometheus:
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0
        addEntryPointsLabels: true
        addServicesLabels: true

entryPoints:
    http:
        address: ':80'
        http:
            redirections:
                entryPoint:
                    to: https
                    permanent: true
    https:
        address: ':443'
        http:
            tls:
                certResolver:
                domains:
                    - main: topi.wtf
                      sans:
                          - 'traefik.topi.wtf'
                          - 'pihole.topi.wtf'
                          - 'tautulli.topi.wtf'
                          - 'plex.topi.wtf'
                          - 'sonarr.topi.wtf'
                          - 'radarr.topi.wtf'
                          - 'jackett.topi.wtf'
                          - 'deluge.topi.wtf'
                          - 'www.topi.wtf'

providers:
    docker:
        exposedByDefault: false
        network: traefik
    file:
        directory: '/configs'

api:
    dashboard: true

certificatesResolvers:
    tls:
        acme:
            # testing server
            # caserver: https://acme-staging-v02.api.letsencrypt.org/directory
            email: tobi@strasserhof.com
            storage: /letsencrypt/acme.json
            tlsChallenge: true
